### PR TITLE
hnj_hyphen_hyphword: fix buffer overflow

### LINKED ISSUE #11: segfault in hnj_hyphen_hyphword
Forwarding issue hunspell/hunspell#12. Closing there.

> In hnj_hyphen_hyphword function hyphenated word length is defined as initial word length plus 5.
> 
> void hnj_hyphen_hyphword(const char * word, int l, const char * hyphens, 
> char * hyphword, char *** rep, int ** pos, int ** cut)
> {
> int hyphenslen = l + 5;
> 
> Then if compound hyphen is found we have:
> 
> if (*rep && *pos && *cut && (*rep)[i]) {
> size_t offset = j - (*pos)[i] + 1;
> strncpy(hyphword + offset, (*rep)[i], hyphenslen - offset - 1);
> hyphword[hyphenslen-1] = '\0';
> j += strlen((*rep)[i]) - (*pos)[i];
> i += (*cut)[i] - (*pos)[i];
> } else hyphword[++j] = '=';
> 
> It leads to problems in a situation when there are more then 5 hyphens in a word followed by compound hyphen.
> In the best scenario hyphenated word is truncated. In worst there is a segmentation fault – strncpy size argument (hyphenslen - offset -1) gets negative value.
> 
> To reproduce:
> echo "mamamamamamammammamamamaasszony" | ./example /usr/share/hyphen/hyph_hu_HU.dic /dev/stdin
> Segmentation fault
> 
> or more practic example:
> echo "application-to-be-used-with-not-so-many" | ./example /usr/share/hyphen/hyph_en_US.dic /dev/stdin
> Segmentation fault

### PR DESCRIPTION
**Pull request by bfabiszewski**
This fixes #11,  a bug I found 5 years ago

### CODE REVIEW

File: hyphen.c [hunk 1]
```diff
@@ -1076,17 +1076,20 @@ int hnj_hyphen_norm(const char *word, int word_size, char * hyphens,
 void hnj_hyphen_hyphword(const char * word, int l, const char * hyphens, 
     char * hyphword, char *** rep, int ** pos, int ** cut)
 {
-  int hyphenslen = l + 5;
+  /* hyphword buffer size must be at least 2 * l */
+  int hyphword_len = 2 * l - 1;
```
Comment (phajdan) [inline hyphen.c]: Since we're starting to be precise, should this also check for possible overflow?

Just in case, these were helpful for me:

http://stackoverflow.com/questions/1815367/multiplication-of-large-numbers-how-to-catch-overflow

https://www.securecoding.cert.org/confluence/display/c/INT32-C.+Ensure+that+operations+on+signed+integers+do+not+result+in+overflow

File: hyphen.c [hunk 2]
```diff
@@ -1076,17 +1076,20 @@ int hnj_hyphen_norm(const char *word, int word_size, char * hyphens,
...
       if (*rep && *pos && *cut && (*rep)[i]) {
-        size_t offset = j - (*pos)[i] + 1;
-        strncpy(hyphword + offset, (*rep)[i], hyphenslen - offset - 1);
-        hyphword[hyphenslen-1] = '\0';
-        j += strlen((*rep)[i]) - (*pos)[i];
+        j -= (*pos)[i] - 1;
+        size_t rep_len = strlen((*rep)[i]);
+        if (j + rep_len > hyphword_len)
+          break;
+        strcpy(hyphword + j, (*rep)[i]);
```
Comment (phajdan) [inline hyphen.c]: IMO the previous style (strncpy) is generally better than some checks followed by strcpy.

Can we somehow still use more secure functions, just making sure not to get negative/wrapping offsets?

File: hyphen.c (hunk 1 above)
Comment (bfabiszewski) [inline hyphen.c]: Thanks for feedback!
You are right. 
Using unsigned type should be ok in this case I think. Something like:
` unsigned int hyphword_len = (l > 0) ? 2 * (unsigned int) l - 1 : 0;`

Yet I'll have a look at it.

File: hyphen.c (hunk 2 above)
Comment (bfabiszewski) [inline hyphen.c]: Here I am not sure.
I still want to check for the overflow to break off the loop. Then it makes using secure copy redundant.

File: hyphen.c (hunk 1 above)
Comment (phajdan) [inline hyphen.c]: I'm not sure if above would be sufficient.

Unsigned operations can wrap: https://www.securecoding.cert.org/confluence/display/c/INT30-C.+Ensure+that+unsigned+integer+operations+do+not+wrap

Admittedly I'm not an expert about this, just wanted to be careful.

File: hyphen.c (hunk 2 above)
Comment (phajdan) [inline hyphen.c]: There's nothing wrong with defense in depth. I strongly recommend we use it, even if to just make the code easier to reason about.

File: hyphen.c (hunk 1 above)
Comment (bfabiszewski) [inline hyphen.c]: I believe that it is sane to assume `UINT_MAX > 2 * INT_MAX`. 
But if you prefer we may also include <limits.h> and do an explicit check.

File: hyphen.c (hunk 2 above)
Comment (bfabiszewski) [inline hyphen.c]: Ok. I will try to improve it.

**Comment by bfabiszewski** [comment]
@phajdan
Thanks again for reviewing. Your comments encouraged me to check everything once again and I found that my previous code was still vulnerable to some corner case overflows.
I rewrote the function to add more checking.

**Comment by phajdan** [comment]
Thank you for the fixes! :)

**Comment by bfabiszewski** [comment]
Thanks!
